export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS"
export const GET_LOCATION_REQUEST = "GET_LOCATION_REQUEST"
export const GET_LOCATION_FAILURE = "GET_LOCATION_FAILURE"

export const GET_API_SUCCESS = "GET_API_SUCCESS"
export const GET_API_REQUEST = "GET_API_REQUEST"
export const GET_API_FAILURE = "GET_API_FAILURE"

export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST"
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS"
export const GET_SEARCH_FAILURE = "GET_SEARCH_FAILURE"
